auto_checkpoint: false

proxy:
  record_path: "EXPERIMENT/TulipMania/LLM/records"
  communication:
    store_path: "EXPERIMENT/TulipMania/LLM/communication"
  monitoring:
    metrics_path: "EXPERIMENT/TulipMania/LLM/monitoring/metrics"
    events_path: "EXPERIMENT/TulipMania/LLM/monitoring/events"
