# LossAversion Rule Persona Configuration

market:
  type: proxy
  checkpoint_dir: "EXPERIMENT/LossAversion/Rule/records/market/checkpoints"
  record_path: "EXPERIMENT/LossAversion/Rule/records/market"
  monitoring:
    record_path: "EXPERIMENT/LossAversion/Rule/monitoring/market"

loss_averse_investor_1_1:
  type: player
  checkpoint_dir: "EXPERIMENT/LossAversion/Rule/records/loss_averse_investor_1_1/checkpoints"
  record_path: "EXPERIMENT/LossAversion/Rule/records/loss_averse_investor_1_1"
  monitoring:
    record_path: "EXPERIMENT/LossAversion/Rule/monitoring/loss_averse_investor_1_1"

loss_averse_investor_1_2:
  type: player
  checkpoint_dir: "EXPERIMENT/LossAversion/Rule/records/loss_averse_investor_1_2/checkpoints"
  record_path: "EXPERIMENT/LossAversion/Rule/records/loss_averse_investor_1_2"
  monitoring:
    record_path: "EXPERIMENT/LossAversion/Rule/monitoring/loss_averse_investor_1_2"

break_even_trader_2_1:
  type: player
  checkpoint_dir: "EXPERIMENT/LossAversion/Rule/records/break_even_trader_2_1/checkpoints"
  record_path: "EXPERIMENT/LossAversion/Rule/records/break_even_trader_2_1"
  monitoring:
    record_path: "EXPERIMENT/LossAversion/Rule/monitoring/break_even_trader_2_1"

break_even_trader_2_2:
  type: player
  checkpoint_dir: "EXPERIMENT/LossAversion/Rule/records/break_even_trader_2_2/checkpoints"
  record_path: "EXPERIMENT/LossAversion/Rule/records/break_even_trader_2_2"
  monitoring:
    record_path: "EXPERIMENT/LossAversion/Rule/monitoring/break_even_trader_2_2"

rational_trader_3_1:
  type: player
  checkpoint_dir: "EXPERIMENT/LossAversion/Rule/records/rational_trader_3_1/checkpoints"
  record_path: "EXPERIMENT/LossAversion/Rule/records/rational_trader_3_1"
  monitoring:
    record_path: "EXPERIMENT/LossAversion/Rule/monitoring/rational_trader_3_1"

momentum_trader_4_1:
  type: player
  checkpoint_dir: "EXPERIMENT/LossAversion/Rule/records/momentum_trader_4_1/checkpoints"
  record_path: "EXPERIMENT/LossAversion/Rule/records/momentum_trader_4_1"
  monitoring:
    record_path: "EXPERIMENT/LossAversion/Rule/monitoring/momentum_trader_4_1"

momentum_trader_4_2:
  type: player
  checkpoint_dir: "EXPERIMENT/LossAversion/Rule/records/momentum_trader_4_2/checkpoints"
  record_path: "EXPERIMENT/LossAversion/Rule/records/momentum_trader_4_2"
  monitoring:
    record_path: "EXPERIMENT/LossAversion/Rule/monitoring/momentum_trader_4_2"

market_maker_5_1:
  type: player
  checkpoint_dir: "EXPERIMENT/LossAversion/Rule/records/market_maker_5_1/checkpoints"
  record_path: "EXPERIMENT/LossAversion/Rule/records/market_maker_5_1"
  monitoring:
    record_path: "EXPERIMENT/LossAversion/Rule/monitoring/market_maker_5_1"

