"""LTCMCollapse RuleLLM Prompts

System prompts for RuleLLM agents using LangChainAPIInference (lmbase).
Each prompt defines an investor personality WITHOUT naming the specific crisis.
"""

from examples.LTCMCollapse.LLM.prompts import (
    LLM_CONVERGENCEARBITRAGEUR_PROMPT as RULELLM_CONVERGENCEARBITRAGEUR_PROMPT,
    LLM_LEVERAGETRADER_PROMPT as RULELLM_LEVERAGETRADER_PROMPT,
    LLM_RISKMANAGER_PROMPT as RULELLM_RISKMANAGER_PROMPT,
    LLM_LIQUIDITYPROVIDER_PROMPT as RULELLM_LIQUIDITYPROVIDER_PROMPT,
    LLM_CENTRALBANK_PROMPT as RULELLM_CENTRALBANK_PROMPT,
)

__all__ = [
    "RULELLM_CONVERGENCEARBITRAGEUR_PROMPT",
    "RULELLM_LEVERAGETRADER_PROMPT",
    "RULELLM_RISKMANAGER_PROMPT",
    "RULELLM_LIQUIDITYPROVIDER_PROMPT",
    "RULELLM_CENTRALBANK_PROMPT",
]
