"""
General Player Implementation for MASim Framework.

This module provides ready-to-use Player implementations that extend BasePlayer.
Use GeneralPlayer as:
    1. A starting point for quick prototyping
    2. A reference implementation showing how to extend BasePlayer
    3. A base class for domain-specific players

For abstract definitions and documentation, see base.py.
"""

import time
from typing import Any, Dict, List, Optional, TYPE_CHECKING

from masim.player.base import (
    BasePlayer,
    PlayerConfig,
    Action,
    Observation,
    LocalObservation,
    PayloadType,
    StepResult,
    TurnResult,
    Outbound,
)

if TYPE_CHECKING:
    from masim.communication.base import Message


# =============================================================================
#                          PLAYER STATE
# =============================================================================


class PlayerState:
    """
    Private state container for Player entities.

    ┌─────────────────────────────────────────────────────────────────────┐
    │                    PRIVACY BOUNDARY                                  │
    │                                                                      │
    │  PlayerState is INVISIBLE to:                                       │
    │    ✗ Coordinator players (cannot see other Player's internal state) │
    │    ✗ Other Players (no direct state access)                         │
    │    ✗ Environment (only sees Actions, not internal reasoning)        │
    │                                                                      │
    │  This privacy is FUNDAMENTAL to multi-agent systems:                │
    │    - Enables strategic/competitive behavior                         │
    │    - Models real-world information asymmetry                        │
    │    - Prevents "cheating" by omniscient coordinators                 │
    └─────────────────────────────────────────────────────────────────────┘

    State Components:
    -----------------
    - turn_count: Number of turns executed (perceive→decide→act cycles)
    - step_count: Number of internal steps within current turn
    - last_observation: Most recent observation received
    - last_action: Most recent action generated
    - custom_state: Flexible key-value store for domain logic
    - message_inbox: Pending messages from CommunicationProxy
    """

    def __init__(self):
        """Initialize empty state container."""
        # Tracks how many perceive→decide→act turns have been executed.
        self.turn_count: int = 0

        # Caches the most recent observation received from the environment.
        self.last_observation: Optional[Observation] = None

        # Caches the most recent action generated by this Player.
        self.last_action: Optional[Action] = None

        # Flexible key-value store for domain-specific state.
        self.custom_state: Dict[str, Any] = {}

        # Queue for outbound messages declared by Player.
        self.pending_outbounds: List["Outbound"] = []

        # Message inbox - stores messages received from other players.
        self.message_inbox: List["Message"] = []

        # Expected senders for readiness checking.
        self.expected_senders: set = set()

        # Execution clock for turn-level timing.
        self.turn_clock_start: Optional[float] = None
        self.turn_last_duration_ms: float = 0.0
        self.turn_total_duration_ms: float = 0.0

        # Step tracking for internal iterations within decide().
        self.step_count: int = 0
        self.step_clock_start: Optional[float] = None
        self.step_last_duration_ms: float = 0.0
        self.step_total_duration_ms: float = 0.0

    def turn_tick_start(self) -> None:
        """Mark the start of a turn execution."""
        self.turn_clock_start = time.perf_counter()

    def turn_tick_end(self) -> None:
        """Mark the end of a turn and calculate duration."""
        if self.turn_clock_start is not None:
            elapsed = time.perf_counter() - self.turn_clock_start
            self.turn_last_duration_ms = elapsed * 1000.0
            self.turn_total_duration_ms += self.turn_last_duration_ms
            self.turn_clock_start = None

    def step_reset(self) -> None:
        """Reset step counters for a new turn."""
        self.step_count = 0
        self.step_total_duration_ms = 0.0
        self.step_last_duration_ms = 0.0
        self.step_clock_start = None

    def step_tick_start(self) -> None:
        """Mark the start of an internal step."""
        self.step_clock_start = time.perf_counter()

    def step_tick_end(self) -> None:
        """Mark the end of a step and update metrics."""
        if self.step_clock_start is not None:
            elapsed = time.perf_counter() - self.step_clock_start
            self.step_last_duration_ms = elapsed * 1000.0
            self.step_total_duration_ms += self.step_last_duration_ms
            self.step_count += 1
            self.step_clock_start = None

    def get_step_metrics(self) -> Dict[str, Any]:
        """Get step timing metrics for the current turn."""
        return {
            "step_count": self.step_count,
            "step_last_duration_ms": round(self.step_last_duration_ms, 3),
            "step_total_duration_ms": round(self.step_total_duration_ms, 3),
            "step_avg_duration_ms": (
                round(self.step_total_duration_ms / self.step_count, 3)
                if self.step_count > 0
                else 0.0
            ),
        }

    def update_turn(self, observation: Observation, action: Action) -> None:
        """Update state after completing a turn."""
        self.last_observation = observation
        self.last_action = action

    def update_step(self, observation: Observation, action: Action) -> None:
        """Update state after completing a step."""
        self.last_observation = observation
        self.last_action = action

    def get_turn_metrics(self) -> Dict[str, Any]:
        """Get turn timing metrics for reporting/logging."""
        return {
            "turn_count": self.turn_count,
            "turn_last_duration_ms": round(self.turn_last_duration_ms, 3),
            "turn_total_duration_ms": round(self.turn_total_duration_ms, 3),
            "turn_avg_duration_ms": (
                round(self.turn_total_duration_ms / self.turn_count, 3)
                if self.turn_count > 0
                else 0.0
            ),
        }

    def get_custom(self, key: str) -> Any:
        """Get a custom state value."""
        return self.custom_state[key]

    def has_custom(self, key: str) -> bool:
        """Check if a custom state key exists."""
        return key in self.custom_state

    def set_custom(self, key: str, value: Any) -> None:
        """Set a custom state value."""
        self.custom_state[key] = value

    def is_ready_to_proceed(self) -> bool:
        """Check if all expected messages have been received."""
        if not self.expected_senders:
            return True
        received_senders = {msg.sender_id for msg in self.message_inbox}
        return self.expected_senders.issubset(received_senders)


# =============================================================================
#                          GENERAL PLAYER
# =============================================================================


class GeneralPlayer(BasePlayer):
    """
    Ready-to-use Player implementation with sensible defaults.

    GeneralPlayer provides a complete implementation of the Player lifecycle
    including initialization, step/turn execution, message handling, and
    state management. It can be:

    1. Used directly for testing and prototyping
    2. Extended for domain-specific behavior

    Default Behavior:
    -----------------
    - perceive(): Stores observation in custom_state["last_observation"]
    - decide(): Returns the observation data as-is
    - act(): Creates an Action with type "default" and the decision payload
    """

    def __init__(self, config: PlayerConfig):
        """Initialize the GeneralPlayer with configuration."""
        # Core Identity
        self.name: str = config.name
        self.identity: str = config.identity
        self.group_tags: List[str] = config.group_tags.copy()
        self.config: PlayerConfig = config

        # Private State Container
        self.state: PlayerState = PlayerState()

        # Capability Tags
        if "capabilities" in config.extras:
            self.capabilities: List[str] = config.extras["capabilities"].copy()
        else:
            self.capabilities: List[str] = []

        # Lifecycle Flags
        self.is_initialized: bool = False
        self.is_running: bool = False

        # Topology Targets
        self.topology_targets: List[str] = []

    # =========================================================================
    #          OBSERVABLEENTITY PROTOCOL IMPLEMENTATION
    # =========================================================================

    def save_state(self) -> Dict[str, Any]:
        """Return state that should be persisted by StorageProxy."""
        return {
            "turn_count": self.state.turn_count,
            "custom_state": self.state.custom_state.copy(),
        }

    def load_state(self, state: Dict[str, Any]) -> None:
        """Restore state from persisted data."""
        if "turn_count" in state:
            self.state.turn_count = state["turn_count"]
        elif "step_count" in state:
            self.state.turn_count = state["step_count"]
        else:
            raise KeyError("State must contain 'turn_count' or 'step_count'")
        self.state.custom_state = state["custom_state"].copy()

    # =========================================================================
    #                           LIFECYCLE
    # =========================================================================

    async def initialize(self) -> None:
        """Initialize the Player for simulation."""
        self.is_initialized = True

    async def shutdown(self) -> None:
        """Shutdown the Player after simulation."""
        self.is_running = False

    # =========================================================================
    #              CORE BEHAVIORAL CONTRACT (Override these)
    # =========================================================================

    async def perceive(
        self,
        observation: Observation,
        prev_result: Optional["StepResult"] = None,
    ) -> None:
        """Process incoming observation and update internal state."""
        self.state.set_custom("last_observation", observation.data)
        if prev_result and prev_result.action:
            self.state.set_custom("prev_action", prev_result.action)

    async def decide(self) -> PayloadType:
        """Make a decision based on current state."""
        return self.state.get_custom("last_observation")

    async def act(self, decision_payload: PayloadType) -> Action:
        """Transform decision into an Action."""
        return Action(
            action_type="default",
            payload=(
                decision_payload
                if isinstance(decision_payload, dict)
                else {"data": decision_payload}
            ),
            source_id=self.identity,
        )

    # =========================================================================
    #                        MAIN EXECUTION
    # =========================================================================

    async def step(
        self,
        observation: Observation,
        prev_result: Optional["StepResult"] = None,
    ) -> "StepResult":
        """Execute one atomic step: perceive → decide → act."""
        self.state.step_tick_start()

        await self.perceive(observation, prev_result)
        decision_payload = await self.decide()

        # Extract outbound messages from decision
        if (
            isinstance(decision_payload, dict)
            and "outbound_messages" in decision_payload
        ):
            raw_messages = decision_payload.pop("outbound_messages", [])
            for msg in raw_messages:
                if isinstance(msg, Outbound):
                    self.state.pending_outbounds.append(msg)
                elif isinstance(msg, dict):
                    self.state.pending_outbounds.append(Outbound(**msg))

        action = await self.act(decision_payload)
        self.state.update_step(observation, action)
        self.state.step_tick_end()

        return StepResult(
            decision_payload=decision_payload,
            action=action,
            tick_step_count=self.state.step_count,
            tick_step_duration_ms=self.state.step_last_duration_ms,
        )

    def prepare_observation(
        self,
        notification: Dict[str, Any],
        round_num: int,
    ) -> Observation:
        """Prepare the Observation for this turn."""
        return Observation(
            local=LocalObservation(data={}),
            notification=notification,
            round=round_num,
        )

    async def turn(
        self,
        notification: Dict[str, Any],
        round_num: int,
        num_steps: int = 1,
    ) -> "TurnResult":
        """Execute a turn consisting of multiple steps."""
        observation = self.prepare_observation(notification, round_num)
        self.state.turn_tick_start()

        step_results: List[StepResult] = []
        current_observation = observation
        prev_result: Optional[StepResult] = None

        for _ in range(num_steps):
            step_result = await self.step(current_observation, prev_result)
            step_results.append(step_result)
            prev_result = step_result
            current_observation = self._update_observation_for_next_step(
                current_observation, step_result
            )

        self.state.turn_count += 1
        self.state.turn_tick_end()

        return TurnResult(
            step_results=step_results,
            final_action=step_results[-1].action if step_results else None,
            tick_turn_count=self.state.turn_count,
            tick_turn_duration_ms=self.state.turn_last_duration_ms,
            tick_turn_total_duration_ms=self.state.turn_total_duration_ms,
            tick_step_count=len(step_results),
        )

    def _update_observation_for_next_step(
        self,
        current_observation: Observation,
        step_result: "StepResult",
    ) -> Observation:
        """Update observation for the next step."""
        return current_observation

    # =========================================================================
    #                      TOPOLOGY ACCESS
    # =========================================================================

    def can_send_to(self, target_id: str) -> bool:
        """Check if this player can send to a specific target."""
        return target_id in self.topology_targets

    # =========================================================================
    #                      MESSAGE HANDLING
    # =========================================================================

    def on_message(self, message: "Message") -> None:
        """Receive a message from another player."""
        self.state.message_inbox.append(message)

    def get_pending_messages(self) -> List["Message"]:
        """Get and clear pending messages from inbox."""
        messages = self.state.message_inbox.copy()
        self.state.message_inbox.clear()
        return messages

    def is_proceed(self) -> bool:
        """Check if player is ready to proceed with execution."""
        return self.state.is_ready_to_proceed()

    # =========================================================================
    #                          UTILITY
    # =========================================================================

    def in_group(self, tag: str) -> bool:
        """Check if this Player belongs to a specific group."""
        return tag in self.group_tags

    def __repr__(self) -> str:
        """String representation for debugging."""
        return f"Player(id={self.identity}, groups={self.group_tags})"


# =============================================================================
#                       SPECIALIZED PLAYERS
# =============================================================================


class EchoPlayer(GeneralPlayer):
    """A Player that echoes back observations with minimal processing."""

    async def act(self, decision_payload: PayloadType) -> Action:
        """Create an echo action with observation data."""
        return Action(
            action_type="echo",
            payload={"echoed_data": decision_payload},
            source_id=self.identity,
            metadata={"player_name": self.name},
        )


class NoOpPlayer(GeneralPlayer):
    """A Player that takes no action (returns empty actions)."""

    async def decide(self) -> PayloadType:
        """Always decide to do nothing."""
        return {"noop": True}

    async def act(self, decision_payload: PayloadType) -> Action:
        """Create a no-op action."""
        return Action(
            action_type="noop",
            payload={},
            source_id=self.identity,
        )


class ReactivePlayer(GeneralPlayer):
    """A Player that reacts based on observation triggers."""

    async def decide(self) -> PayloadType:
        """Decide based on reactive triggers."""
        obs = self.state.get_custom("last_observation")

        if self.should_react(obs):
            return self.create_reaction(obs)
        return self.create_default_response(obs)

    def should_react(self, observation: Dict[str, Any]) -> bool:
        """Determine if a reaction is needed."""
        return False

    def create_reaction(self, observation: Dict[str, Any]) -> Dict[str, Any]:
        """Create a reaction payload when triggered."""
        return {"reaction": True, "triggered_by": observation}

    def create_default_response(self, observation: Dict[str, Any]) -> Dict[str, Any]:
        """Create default response when not reacting."""
        return {"reaction": False, "hold": True}
