# SorosPound Rag Topology Configuration

type: "star"

sources:
  - market

connections:
  market:
    - ragllm_macro_hedge_fund
    - ragllm_peg_defender
    - ragllm_convergence_trader
    - ragllm_opportunistic_trader
    - ragllm_noise_trader
  ragllm_macro_hedge_fund:
    - market
  ragllm_peg_defender:
    - market
  ragllm_convergence_trader:
    - market
  ragllm_opportunistic_trader:
    - market
  ragllm_noise_trader:
    - market
