"""Shared, event-neutral H2EPR Rule execution closure helpers."""

from .closure import (
    CompactRunClosure,
    RunClosureCode,
    RunClosureError,
    RunClosureSummary,
    build_formal_run_documents,
    build_graph_receipt,
    compare_run_artifacts,
    validate_compact_run_closure,
    validate_run_artifacts,
)
from .custody import (
    RunCustodyError,
    RunCustodyIdentity,
    materialize_run_pair,
    require_fresh_directory,
)
from .io import ExecutionIOCode, ExecutionIOError, path_within, read_json_object
from .lifecycle import (
    LifecycleRecord,
    LifecycleRule,
    LifecycleRuleError,
    LifecycleTransitionResult,
    chain_states,
)
from .model import (
    FORMAL_RUN_DOCUMENTS,
    RUN_DOCUMENTS,
    RunArtifacts,
    RunArtifactsLike,
    RunComparisonIdentity,
    RunPair,
    document_descriptor,
    plain_data,
    run_documents,
    serialized_json_bytes,
    source_sha256_bytes,
    source_sha256_path,
)
from .participant import (
    DecisionSpec,
    IntentBranch,
    ParticipantDecision,
    ParticipantDecisionContext,
    ParticipantPolicyError,
    RuleParticipantPolicy,
)

__all__ = [
    "CompactRunClosure",
    "DecisionSpec",
    "ExecutionIOCode",
    "ExecutionIOError",
    "FORMAL_RUN_DOCUMENTS",
    "IntentBranch",
    "LifecycleRecord",
    "LifecycleRule",
    "LifecycleRuleError",
    "LifecycleTransitionResult",
    "ParticipantDecision",
    "ParticipantDecisionContext",
    "ParticipantPolicyError",
    "RUN_DOCUMENTS",
    "RunArtifacts",
    "RunArtifactsLike",
    "RunClosureCode",
    "RunClosureError",
    "RunClosureSummary",
    "RunComparisonIdentity",
    "RunCustodyError",
    "RunCustodyIdentity",
    "RunPair",
    "RuleParticipantPolicy",
    "build_formal_run_documents",
    "build_graph_receipt",
    "chain_states",
    "compare_run_artifacts",
    "document_descriptor",
    "materialize_run_pair",
    "path_within",
    "plain_data",
    "read_json_object",
    "require_fresh_directory",
    "run_documents",
    "serialized_json_bytes",
    "source_sha256_bytes",
    "source_sha256_path",
    "validate_compact_run_closure",
    "validate_run_artifacts",
]
