# Topology configuration

type: "star"

sources:
  - market

connections:
  market:
    - rule_speculative_attacker
    - rule_self_fulfilling_trader
    - rule_central_bank_defender
    - rule_fundamental_hedger
    - rule_noise_trader
  rule_central_bank_defender:
    - market
  rule_fundamental_hedger:
    - market
  rule_noise_trader:
    - market
  rule_self_fulfilling_trader:
    - market
  rule_speculative_attacker:
    - market
