# Topology configuration
connections:
  - source: market
    target: recenteventoverweighter
  - source: recenteventoverweighter
    target: market
  - source: market
    target: mediainfluencedtrader
  - source: mediainfluencedtrader
    target: market
  - source: market
    target: systematicanalyst
  - source: systematicanalyst
    target: market
  - source: market
    target: valuetrader
  - source: valuetrader
    target: market
  - source: market
    target: noisetrader
  - source: noisetrader
    target: market
