#!/usr/bin/env python
"""Default-AnchoringEffect-Rule-r100 — Customized Simulation Runner.

Auto-generated by the Customized Simulation Builder.
Scenario: AnchoringEffect

Usage:
    python examples/CUSTOMIZED_SIMULATION/Default-AnchoringEffect-Rule-r100/run_customized.py \
        -c configs/CUSTOMIZED_SIMULATION/Default-AnchoringEffect-Rule-r100/simulation.yml
"""

import argparse
import asyncio

from masim.simulator.base import SimulationConfig
from masim.simulator.general import GeneralSimulator
from masim.utils.config import load_config, setup_logging


DEFAULT_CONFIG = "configs/CUSTOMIZED_SIMULATION/Default-AnchoringEffect-Rule-r100/simulation.yml"


async def main():
    setup_logging()

    parser = argparse.ArgumentParser(
        description="Run customized simulation Default-AnchoringEffect-Rule-r100 (scenario: AnchoringEffect)"
    )
    parser.add_argument(
        "-c",
        "--config",
        type=str,
        default=DEFAULT_CONFIG,
    )
    args = parser.parse_args()

    yaml_config = load_config(args.config)
    config = SimulationConfig(**yaml_config)

    print("\n" + "=" * 70)
    print("Default-AnchoringEffect-Rule-r100 — Customized Simulation")
    print("=" * 70)
    print("Scenario:      AnchoringEffect")
    print("Rounds:        %s" % config.setting["total_rounds"])
    print("=" * 70 + "\n")

    simulator = GeneralSimulator(config)

    try:
        await simulator.setup()
        results = await simulator.run()
        print("\n" + "=" * 70)
        print("Simulation Complete!")
        print("=" * 70)
    finally:
        await simulator.shutdown()


if __name__ == "__main__":
    asyncio.run(main())
