"""
Event Cascade Visualization Test Script
=======================================

This script demonstrates how to visualize a financial event cascade using the EventCascadeVisualizer.
It loads a JSON file containing the reconstructed event data (EventCascade) and generates a
timeline visualization image.

Usage:
    Run this script from the project root directory:

    Run:
    python examples/uTEST/Builder/test_viz.py
"""

import os
import json
import sys
import matplotlib.pyplot as plt
from finmy.builder.agent_build.visualizer import EventCascadeVisualizer

interactive = ("--interactive" in sys.argv) or (
    os.environ.get("INTERACTIVE_VIZ") == "1"
)
if not interactive:
    plt.switch_backend("Agg")


def test_visualization():
    """
    Main function to run the visualization test.

    Steps:
    1. Define path to the input JSON file (IntegratedEventCascade.json).
    2. Load the JSON data.
    3. Initialize the EventCascadeVisualizer.
    4. Generate and save the visualization to a PNG file.
    """

    # --- 1. Define Input Data Path ---

    # We use the experimental data generated by the StepBuilder
    # Path is relative to the project root
    # json_path = "EXPERIMENT/uTEST/StepBuilderDemo1/FinalEventCascade.json"
    json_path = "EXPERIMENT/uTEST/StepBuilderDemo1/FinalEventCascade.json"

    # Check if the input file exists
    if not os.path.exists(json_path):
        print(f"Error: JSON file not found at {json_path}")
        print(
            "Please ensure you are running this script from the project root and the data exists."
        )
        return

    # --- 2. Initialize Visualizer ---
    print("Initializing EventCascadeVisualizer...")
    viz = EventCascadeVisualizer()

    # --- 3. Generate Visualization ---

    # Output path for the image (saved in the same directory as the input json)
    with open(json_path, "r", encoding="utf-8") as f:
        cascade_data = json.load(f)
    base = os.path.splitext(os.path.basename(json_path))[0]
    out_dir = os.path.dirname(json_path)
    output_path = None if interactive else os.path.join(out_dir, f"{base}_timeline.png")

    print(f"Generating visualization to: {output_path}...")
    try:
        ret = viz.plot_cascade(cascade_data, output_path)

        if interactive:
            plt.show()
        else:
            if os.path.exists(output_path):
                print(f"Success: Visualization successfully generated at {output_path}")
            else:
                print("Error: Output file was not created.")

    except Exception as e:
        print(f"Exception occurred during visualization: {e}")
        import traceback

        traceback.print_exc()


if __name__ == "__main__":
    test_visualization()
