# Topology configuration
connections:
  - source: market
    target: gainframefollower
  - source: gainframefollower
    target: market
  - source: market
    target: lossframereactor
  - source: lossframereactor
    target: market
  - source: market
    target: frameinvarianttrader
  - source: frameinvarianttrader
    target: market
  - source: market
    target: arbitrageframer
  - source: arbitrageframer
    target: market
  - source: market
    target: noisetrader
  - source: noisetrader
    target: market
