# Topology configuration
connections:
  - source: market
    target: endowedholder
  - source: endowedholder
    target: market
  - source: market
    target: statusquoseller
  - source: statusquoseller
    target: market
  - source: market
    target: rationalarbitrageur
  - source: rationalarbitrageur
    target: market
  - source: market
    target: newbuyer
  - source: newbuyer
    target: market
  - source: market
    target: noisetrader
  - source: noisetrader
    target: market
