# StatusQuoBias Rag Topology Configuration

type: "star"

connections:
  market:
    - inertialholder
    - defaultfollower
    - activerebalancer
    - momentumtrader
    - noisetrader
  inertialholder:
    - market
  defaultfollower:
    - market
  activerebalancer:
    - market
  momentumtrader:
    - market
  noisetrader:
    - market
