# GFC2008 Rag Topology - Star Pattern

type: "star"

sources:
  - market

connections:
  market:
    - ragllm_mbs_originator
    - ragllm_leveraged_investor
    - ragllm_rating_agency
    - ragllm_distressed_buyer
    - ragllm_regulator

  ragllm_mbs_originator:
    - market

  ragllm_leveraged_investor:
    - market

  ragllm_rating_agency:
    - market

  ragllm_distressed_buyer:
    - market

  ragllm_regulator:
    - market
