# Topology configuration

type: "star"

sources:
  - market

connections:
  market:
    - speculativeattacker
    - selffulfillingtrader
    - centralbankdefender
    - fundamentalhedger
    - noisetrader
  centralbankdefender:
    - market
  fundamentalhedger:
    - market
  noisetrader:
    - market
  selffulfillingtrader:
    - market
  speculativeattacker:
    - market
