"""Authoritative Rule state graphs for the eleven SingHealth lifecycles."""

from __future__ import annotations

from types import MappingProxyType
from typing import Mapping, Sequence

from h2epr.execution import LifecycleRule, chain_states


ALL_CAPABILITIES = (
    "cluster_information_security_officer",
    "cyber_security_governance_director_and_healthcare_sector_lead",
    "ihis_chief_executive_officer",
    "ihis_operational_and_scm_management",
    "security_incident_response_manager",
    "singhealth_deputy_group_chief_executive_officer",
    "singhealth_group_chief_executive_officer",
    "singhealth_group_chief_information_officer",
    "technical_administration_and_line_security_staff",
)


def _rule(
    family: str,
    *,
    capabilities: Sequence[str],
    states: Sequence[str],
    initials: Sequence[str],
    terminals: Sequence[str],
    transitions: Sequence[tuple[str, str]],
) -> LifecycleRule:
    return LifecycleRule(
        lifecycle_id=f"lifecycle.0616.{family}",
        implementation_id=f"h2epr.lifecycle.0616.{family}",
        implementation_version="0.1.0",
        owner_layer="reducer",
        participant_capability_ids=tuple(capabilities),
        state_ids=tuple(states),
        initial_state_ids=tuple(initials),
        terminal_state_ids=tuple(terminals),
        transitions=tuple(transitions),
    )


PARTICIPANT_INTENT = _rule(
    "participant_intent",
    capabilities=ALL_CAPABILITIES,
    states=(
        "issued",
        "admitted",
        "rejected",
        "pending",
        "acknowledged",
        "partial",
        "completed",
        "failed",
        "expired",
        "cancelled",
        "superseded",
    ),
    initials=("issued",),
    terminals=(
        "rejected",
        "completed",
        "failed",
        "expired",
        "cancelled",
        "superseded",
    ),
    transitions=(
        ("issued", "admitted"),
        ("issued", "rejected"),
        ("issued", "expired"),
        ("issued", "cancelled"),
        ("issued", "superseded"),
        ("admitted", "pending"),
        ("admitted", "acknowledged"),
        ("admitted", "partial"),
        ("admitted", "completed"),
        ("admitted", "failed"),
        ("admitted", "expired"),
        ("admitted", "cancelled"),
        ("admitted", "superseded"),
        ("pending", "acknowledged"),
        ("pending", "partial"),
        ("pending", "completed"),
        ("pending", "failed"),
        ("pending", "expired"),
        ("pending", "cancelled"),
        ("pending", "superseded"),
        ("acknowledged", "partial"),
        ("acknowledged", "completed"),
        ("acknowledged", "failed"),
        ("acknowledged", "cancelled"),
        ("acknowledged", "superseded"),
        ("partial", "completed"),
        ("partial", "failed"),
        ("partial", "expired"),
        ("partial", "cancelled"),
        ("partial", "superseded"),
    ),
)

INFORMATION_PRODUCT = _rule(
    "information_product",
    capabilities=ALL_CAPABILITIES,
    states=(
        "drafted",
        "produced",
        "versioned",
        "routed",
        "delivered",
        "acknowledged",
        "corrected",
        "superseded",
        "stale",
        "expired",
    ),
    initials=("drafted", "produced"),
    terminals=("superseded", "stale", "expired"),
    transitions=(
        ("drafted", "produced"),
        ("produced", "versioned"),
        ("produced", "routed"),
        ("produced", "corrected"),
        ("produced", "superseded"),
        ("produced", "stale"),
        ("produced", "expired"),
        ("versioned", "routed"),
        ("versioned", "corrected"),
        ("versioned", "superseded"),
        ("versioned", "stale"),
        ("versioned", "expired"),
        ("routed", "delivered"),
        ("routed", "corrected"),
        ("routed", "superseded"),
        ("routed", "stale"),
        ("routed", "expired"),
        ("delivered", "acknowledged"),
        ("delivered", "corrected"),
        ("delivered", "superseded"),
        ("delivered", "stale"),
        ("delivered", "expired"),
        ("acknowledged", "corrected"),
        ("acknowledged", "superseded"),
        ("acknowledged", "stale"),
        ("acknowledged", "expired"),
        ("corrected", "routed"),
        ("corrected", "superseded"),
        ("corrected", "stale"),
        ("corrected", "expired"),
    ),
)

INVESTIGATION_OR_VERIFICATION_REQUEST = _rule(
    "investigation_or_verification_request",
    capabilities=ALL_CAPABILITIES,
    states=(
        "requested",
        "authority_checked",
        "assigned",
        "executing",
        "partial",
        "completed",
        "failed",
        "declined",
        "expired",
        "closed",
    ),
    initials=("requested",),
    terminals=("closed",),
    transitions=(
        *chain_states("requested", "authority_checked", "assigned", "executing"),
        ("authority_checked", "declined"),
        ("authority_checked", "expired"),
        ("assigned", "declined"),
        ("assigned", "expired"),
        ("executing", "partial"),
        ("executing", "completed"),
        ("executing", "failed"),
        ("executing", "expired"),
        ("partial", "executing"),
        ("partial", "completed"),
        ("partial", "failed"),
        ("partial", "expired"),
        ("partial", "closed"),
        ("completed", "closed"),
        ("failed", "closed"),
        ("declined", "closed"),
        ("expired", "closed"),
    ),
)

LOCAL_CONTROL_REQUEST = _rule(
    "local_control_request",
    capabilities=(
        "security_incident_response_manager",
        "technical_administration_and_line_security_staff",
    ),
    states=(
        "proposed",
        "authority_checked",
        "scheduled",
        "executing",
        "partial",
        "effective",
        "no_effect",
        "adverse",
        "reversed",
        "released",
    ),
    initials=("proposed",),
    terminals=("released",),
    transitions=(
        *chain_states("proposed", "authority_checked", "scheduled", "executing"),
        ("executing", "partial"),
        ("executing", "effective"),
        ("executing", "no_effect"),
        ("executing", "adverse"),
        ("partial", "effective"),
        ("partial", "no_effect"),
        ("partial", "adverse"),
        ("partial", "reversed"),
        ("partial", "released"),
        ("effective", "reversed"),
        ("effective", "released"),
        ("no_effect", "reversed"),
        ("no_effect", "released"),
        ("adverse", "reversed"),
        ("adverse", "released"),
        ("reversed", "released"),
    ),
)

MEETING_OR_CONSULTATION = _rule(
    "meeting_or_consultation",
    capabilities=tuple(
        item
        for item in ALL_CAPABILITIES
        if item != "technical_administration_and_line_security_staff"
    ),
    states=(
        "requested",
        "admitted",
        "rejected",
        "invited",
        "invitation_partial",
        "attended",
        "no_attendance",
        "material_presented",
        "decision_recorded",
        "action_assigned",
        "record_delivered",
        "closed",
    ),
    initials=("requested",),
    terminals=("closed",),
    transitions=(
        ("requested", "admitted"),
        ("requested", "rejected"),
        ("admitted", "invited"),
        ("invited", "invitation_partial"),
        ("invited", "attended"),
        ("invited", "no_attendance"),
        ("invitation_partial", "attended"),
        ("invitation_partial", "no_attendance"),
        ("attended", "material_presented"),
        ("material_presented", "decision_recorded"),
        ("decision_recorded", "action_assigned"),
        ("decision_recorded", "record_delivered"),
        ("action_assigned", "record_delivered"),
        ("record_delivered", "closed"),
        ("no_attendance", "closed"),
        ("rejected", "closed"),
    ),
)

RESPONSE_TEAM_ACTIVATION = _rule(
    "response_team_activation",
    capabilities=(
        "cluster_information_security_officer",
        "security_incident_response_manager",
    ),
    states=(
        "requested",
        "authority_checked",
        "activated",
        "declined",
        "staffed",
        "partially_staffed",
        "operating",
        "failed",
        "stood_down",
    ),
    initials=("requested",),
    terminals=("declined", "failed", "stood_down"),
    transitions=(
        ("requested", "authority_checked"),
        ("authority_checked", "activated"),
        ("authority_checked", "declined"),
        ("activated", "staffed"),
        ("activated", "partially_staffed"),
        ("activated", "failed"),
        ("staffed", "operating"),
        ("staffed", "stood_down"),
        ("staffed", "failed"),
        ("partially_staffed", "operating"),
        ("partially_staffed", "stood_down"),
        ("partially_staffed", "failed"),
        ("operating", "stood_down"),
        ("operating", "failed"),
    ),
)

INCIDENT_ASSESSMENT_AND_CATEGORY = _rule(
    "incident_assessment_and_category",
    capabilities=(
        "cluster_information_security_officer",
        "cyber_security_governance_director_and_healthcare_sector_lead",
        "ihis_chief_executive_officer",
        "security_incident_response_manager",
    ),
    states=(
        "suspected",
        "under_review",
        "provisionally_assessed",
        "category_proposed",
        "institutionally_classified",
        "revised",
        "reopened",
        "closed",
    ),
    initials=("suspected",),
    terminals=("closed",),
    transitions=(
        ("suspected", "under_review"),
        ("suspected", "closed"),
        ("under_review", "provisionally_assessed"),
        ("under_review", "category_proposed"),
        ("under_review", "closed"),
        ("provisionally_assessed", "category_proposed"),
        ("provisionally_assessed", "closed"),
        ("category_proposed", "institutionally_classified"),
        ("category_proposed", "revised"),
        ("category_proposed", "closed"),
        ("institutionally_classified", "revised"),
        ("institutionally_classified", "reopened"),
        ("institutionally_classified", "closed"),
        ("revised", "under_review"),
        ("revised", "category_proposed"),
        ("revised", "institutionally_classified"),
        ("revised", "closed"),
        ("reopened", "under_review"),
        ("reopened", "closed"),
    ),
)

REPORT_AND_NOTIFICATION = _rule(
    "report_and_notification",
    capabilities=(
        "cluster_information_security_officer",
        "cyber_security_governance_director_and_healthcare_sector_lead",
        "ihis_chief_executive_officer",
        "security_incident_response_manager",
        "singhealth_deputy_group_chief_executive_officer",
        "singhealth_group_chief_executive_officer",
        "singhealth_group_chief_information_officer",
    ),
    states=(
        "proposed",
        "drafted",
        "authorized",
        "authorization_declined",
        "issued",
        "transported",
        "delivered",
        "acknowledged",
        "corrected",
        "superseded",
        "failed",
        "closed",
    ),
    initials=("proposed",),
    terminals=("authorization_declined", "superseded", "failed", "closed"),
    transitions=(
        ("proposed", "drafted"),
        ("drafted", "authorized"),
        ("drafted", "authorization_declined"),
        ("authorized", "issued"),
        ("issued", "transported"),
        ("issued", "corrected"),
        ("issued", "superseded"),
        ("issued", "failed"),
        ("transported", "delivered"),
        ("transported", "corrected"),
        ("transported", "superseded"),
        ("transported", "failed"),
        ("delivered", "acknowledged"),
        ("delivered", "corrected"),
        ("delivered", "superseded"),
        ("delivered", "closed"),
        ("acknowledged", "corrected"),
        ("acknowledged", "superseded"),
        ("acknowledged", "closed"),
        ("corrected", "authorized"),
        ("corrected", "issued"),
        ("corrected", "closed"),
    ),
)

INVESTIGATION_ASSIGNMENT = _rule(
    "investigation_assignment",
    capabilities=(
        "ihis_chief_executive_officer",
        "ihis_operational_and_scm_management",
        "security_incident_response_manager",
    ),
    states=(
        "proposed",
        "authority_checked",
        "accepted",
        "declined",
        "active",
        "partial",
        "completed",
        "failed",
        "reassigned",
        "closed",
    ),
    initials=("proposed",),
    terminals=("closed",),
    transitions=(
        ("proposed", "authority_checked"),
        ("authority_checked", "accepted"),
        ("authority_checked", "declined"),
        ("authority_checked", "reassigned"),
        ("accepted", "active"),
        ("accepted", "reassigned"),
        ("active", "partial"),
        ("active", "completed"),
        ("active", "failed"),
        ("active", "reassigned"),
        ("partial", "active"),
        ("partial", "completed"),
        ("partial", "failed"),
        ("partial", "reassigned"),
        ("completed", "closed"),
        ("failed", "closed"),
        ("declined", "closed"),
        ("reassigned", "closed"),
    ),
)

OUTREACH_PLAN = _rule(
    "outreach_plan",
    capabilities=(
        "singhealth_deputy_group_chief_executive_officer",
        "singhealth_group_chief_executive_officer",
        "singhealth_group_chief_information_officer",
    ),
    states=(
        "preparation_requested",
        "drafting",
        "consultation",
        "revised",
        "readiness_assessed",
        "approved",
        "declined",
        "executing",
        "completed",
        "cancelled",
    ),
    initials=("preparation_requested",),
    terminals=("completed", "cancelled"),
    transitions=(
        ("preparation_requested", "drafting"),
        ("drafting", "consultation"),
        ("drafting", "readiness_assessed"),
        ("consultation", "revised"),
        ("consultation", "readiness_assessed"),
        ("revised", "consultation"),
        ("revised", "readiness_assessed"),
        ("readiness_assessed", "approved"),
        ("readiness_assessed", "declined"),
        ("approved", "executing"),
        ("executing", "completed"),
        ("executing", "cancelled"),
        ("declined", "cancelled"),
    ),
)

ATTACK_AND_TECHNICAL_EFFECT = _rule(
    "attack_and_technical_effect",
    capabilities=(
        "security_incident_response_manager",
        "technical_administration_and_line_security_staff",
    ),
    states=(
        "attempt",
        "access_adjudication",
        "executed",
        "blocked",
        "failed",
        "persisted",
        "detected",
        "contained",
        "later_observed",
    ),
    initials=("attempt",),
    terminals=("later_observed",),
    transitions=(
        ("attempt", "access_adjudication"),
        ("access_adjudication", "executed"),
        ("access_adjudication", "blocked"),
        ("access_adjudication", "failed"),
        ("executed", "persisted"),
        ("executed", "detected"),
        ("executed", "contained"),
        ("executed", "later_observed"),
        ("persisted", "detected"),
        ("persisted", "contained"),
        ("persisted", "later_observed"),
        ("detected", "contained"),
        ("detected", "later_observed"),
        ("contained", "later_observed"),
        ("blocked", "later_observed"),
        ("failed", "later_observed"),
    ),
)


LIFECYCLE_RULES = (
    PARTICIPANT_INTENT,
    INFORMATION_PRODUCT,
    INVESTIGATION_OR_VERIFICATION_REQUEST,
    LOCAL_CONTROL_REQUEST,
    MEETING_OR_CONSULTATION,
    RESPONSE_TEAM_ACTIVATION,
    INCIDENT_ASSESSMENT_AND_CATEGORY,
    REPORT_AND_NOTIFICATION,
    INVESTIGATION_ASSIGNMENT,
    OUTREACH_PLAN,
    ATTACK_AND_TECHNICAL_EFFECT,
)
LIFECYCLE_RULES_BY_ID: Mapping[str, LifecycleRule] = MappingProxyType(
    {rule.lifecycle_id: rule for rule in LIFECYCLE_RULES}
)

if len(LIFECYCLE_RULES_BY_ID) != len(LIFECYCLE_RULES):
    raise ValueError("singhealth_lifecycle_registry_duplicate")


__all__ = [
    "ATTACK_AND_TECHNICAL_EFFECT",
    "INCIDENT_ASSESSMENT_AND_CATEGORY",
    "INFORMATION_PRODUCT",
    "INVESTIGATION_ASSIGNMENT",
    "INVESTIGATION_OR_VERIFICATION_REQUEST",
    "LIFECYCLE_RULES",
    "LIFECYCLE_RULES_BY_ID",
    "LOCAL_CONTROL_REQUEST",
    "MEETING_OR_CONSULTATION",
    "OUTREACH_PLAN",
    "PARTICIPANT_INTENT",
    "REPORT_AND_NOTIFICATION",
    "RESPONSE_TEAM_ACTIVATION",
]
